# Welcome to Jekyll!

# Site settings
title: Yet Another Open Source Blog
email: epsi.nurwijayadi@gmail.com
description: > # description below
  Learn and Discover Open Source with Daily Genuine Experience.
  From Coding, Design, Package Management Tweak to Desktop Customization.
baseurl: "" # the subpath of your site, e.g. /blog

# the base hostname & protocol for your site
# url: "http://epsi-rns.github.io" 
url: "http://localhost:4000" 

# Missing timezone in metadata date can lead to wrong date in url
timezone: Asia/Jakarta

# Build settings
# markdown: kramdown

