#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/epsi/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

xrandr -s 1024x768
feh --bg-scale /home/epsi/Pictures/Wallpapers/colored_background_from_dark_to_colour-1024x768.jpg 
compton -m 0.95 &
volwheel &
nm-applet &
dockx &
conky -d &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/epsi/.fluxbox/log"
